### ISSUE TITLE
So it's me again. I tried the new code by pressing the copy then pasting it. And it did nothing

### ISSUE THREAD

**Issue by RaynerBoniacio** [shenkeYT/blooket-hack#10]

**Comment by shenkeYT** [comment]
what code

**Comment by RaynerBoniacio** [comment]
Didn't you fix the code. Like the one that was taking me to the enter code
page, like your coding that i paste in

**Comment by shenkeYT** [comment]
what code doesent work and i will make sure it works

**Comment by new-hue** [comment]
I think it's crypto hack.

**Comment by new-hue** [comment]
Yep it's crypto hack. The one to get crypto.

**Comment by shenkeYT** [comment]
im fixing it

**Comment by shenkeYT** [comment]
its fixed now

**Comment by oTrentk** [comment]
shenke can you fix gold chest esp pls and thank u sm

**Comment by RaynerBoniacio** [comment]
ok thanks

**Comment by RaynerBoniacio** [comment]
It still takes me to the enter code page once i've entered to script

**Comment by RaynerBoniacio** [comment]
So when i put in the amount i want it gives me it but then if i like do the
questions in the game and say i got the question correct, i'd click on one
of the power up things like where i can get hack and then it just boots me
from the game

**Comment by RaynerBoniacio** [comment]
ok, thanks

**Comment by RaynerBoniacio** [comment]
Awesome, thanks!

**Comment by RaynerBoniacio** [comment]
email me when you've fixed it

**Comment by RaynerBoniacio** [comment]
in crypto. You have to fix the add crypto script
