### ISSUE TITLE
Confused how to use, pls explain

### ISSUE THREAD

**Issue by COleBeV** [shenkeYT/blooket-hack#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

pls star

**Comment by new-hue** [comment]
make a bookmark type `javascript:` then paste in the code. open up blooket and click on the bookmark.

**Comment by MoonLord420** [comment]
I did that but it does not work. I am on a school chromebook.

**Comment by new-hue** [comment]
make sure to click the two squares icon. That will copy the contents.

**Comment by MoonLord420** [comment]
I did. I copied it all and put it in a bookmark.
Is it supposed to be an imported Bookmark?

**Comment by new-hue** [comment]
if it isn't working please let the creator know by making a separate issue.

**Comment by MoonLord420** [comment]
ok

**Comment by new-hue** [comment]
![image](https://user-images.githubusercontent.com/89873236/162027280-af0f4a8c-33b5-4ab0-b038-7b3d0a6040db.png)

**Comment by new-hue** [comment]
that's what the bookmark should look like.

**Comment by MoonLord420** [comment]
![Screenshot 2022-04-06 11 58 14](https://user-images.githubusercontent.com/103135972/162028044-65c79796-3229-4683-8c9f-26f5d220d6ce.png)
This is what it looks like

**Comment by MoonLord420** [comment]
it is the nono

**Comment by MoonLord420** [comment]
And this i the bookmark manager
![Screenshot 2022-04-06 11 59 31](https://user-images.githubusercontent.com/103135972/162028283-808ad291-b483-450a-847a-a040b15849d2.png)

**Comment by RoronoaDLuffy** [comment]
its easy just do ctrl+shift+j then copy the code on whatever ur doing and paste it and hit enter
