### ISSUE TITLE
Code is stolen

### ISSUE THREAD

**Issue by lool3** [shenkeYT/blooket-hack#23]
This code was stolen from 'https://schoolcheats.net/blooket/'. A project that was once hosted on GitHub before it was taken off the platform due to legal issues.

Please stop taking credit for this work, it is simply not yours to take credit for.

**Comment by VexHazity** [comment]
@lool3 
He did not steal the code, he even gave credit to schoolcheats! And if you don't believe me, here is a screenshot of the main page.
![Screenshot 2022-04-12 10 48 39](https://user-images.githubusercontent.com/102967784/163003166-e303ff16-5a4a-453e-b415-e23e1a6617a3.png)

**Comment by smintf** [comment]
> @lool3 He did not steal the code, he even gave credit to schoolcheats! And if you don't believe me, here is a screenshot of the main page. ![Screenshot 2022-04-12 10 48 39](https://user-images.githubusercontent.com/102967784/163003166-e303ff16-5a4a-453e-b415-e23e1a6617a3.png)

Either way that isn't even where near to proper credits and for godsake the README is supposed to be a markdown file, not a regular text file.
