### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by Ismmedero9** [shenkeYT/blooket-hack#3]

**Comment by Ismmedero9** [comment]
The prompt doesn’t show up.

**Comment by shenkeYT** [comment]
yes i am aware blooket have changed theyre website and we are working on a new code it may be down for 1/2 days sorry for the inconvienience

**Comment by Ismmedero9** [comment]
Oh, ok sorry for troubling you.

**Comment by shenkeYT** [comment]
no problem
