### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CloudzFN999** [shenkeYT/blooket-hack#31]
Hey there Shenke,

I have been using a school computer, every time I try using the blooket hacks they tell me to go to https://schoolcheats.net/blooket.
and when I go there it is blocked so can you please fix this hack by making it like the bookmark one again

**Comment by Packjackisback** [comment]
The issue is they are outdated. Give him a bit

**Comment by CloudzFN999** [comment]
Ok Thank you, sorry for bothering.
