### ISSUE TITLE
Add Daily Tokens isn't doing anything

### ISSUE THREAD

**Issue by DragonDude20** [shenkeYT/blooket-hack#43]
I copied the hack, then went to dashboard.blooket.com/market and typed javascript: in the URL bar, and then pasted it. But it did nothing. What's happening?

I also tested the whole Global folder. None of it works.

**Comment by Gitry305** [comment]
you are right

**Comment by DragonDude20** [comment]
I’m also starting to wonder if any of the other hacks work. They haven’t been updated for a while.

**Comment by DragonDude20** [comment]
You seem to have a lot of experience with this kind of code. What do you think is happening?
