### ISSUE TITLE
Stolen Code

### ISSUE THREAD

**Issue by vantr-o** [shenkeYT/blooket-hack#49]
All of these scripts are stolen from School Cheats, it's obvious looking at the first part which makes every bit of code expire every 24 hours. Learn to code your own scripts rather than hosting non working hacks.

**Comment by vantr-o** [comment]
Don't close this like you do with everything else or I will get this taken down.

**Comment by fluid-beam** [comment]
welp he did it

**Comment by fluid-beam** [comment]
same

**Comment by fluid-beam** [comment]
the original message did get emailed to everyone whos subscribed though so we all know now ig. Another way to tell is that when you put it in the console it gives an error message saying dont post things from schoolhacks.com so its easy to tell

**Comment by vantr-o** [comment]
> the original message did get emailed to everyone whos subscribed though so we all know now ig. Another way to tell is that when you put it in the console it gives an error message saying dont post things from schoolhacks.com so its easy to tell

I'll be getting this taken down no worries.

**Comment by vantr-o** [comment]
"edited by shenkeYT"
![image](https://user-images.githubusercontent.com/113489420/191812397-979d53bb-75c1-49d7-b1f6-a638ee88dde7.png)

**Comment by vantr-o** [comment]
stop trying.
