### ISSUE TITLE
invalid reason

### ISSUE THREAD

**Issue by kgsensei** [shenkeYT/blooket-hack#5]
**Describe the bug**
This is not the original or the first blooket hack.

**Comment by Hakxs** [comment]
its a copy and a good one

**Comment by shenkeYT** [comment]
I copy it from a website and change the codes in certain areas

**Comment by smintf** [comment]
> I copy it from a website and change the codes in certain areas

how do u ***"change"*** code that is legit obfuscated?

**Comment by kgsensei** [comment]
lmao true

**Comment by smintf** [comment]
it's pretty obv that he just can't code.

**Comment by smintf** [comment]
the fact the `README` file is obv a markdown file and yet doesn't have the proper file extension is more telling.
