### ISSUE TITLE
anyone having and issue click here: stolen code

### ISSUE THREAD

**Issue by Jude-Gideon** [shenkeYT/blooket-hack#55]
This user [shenkeYT](https://github.com/shenkeYT) does not make these. These are stolen codes from https://schoolcheats.net 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/113489420/192832660-400f8e36-c9d3-4d15-a857-03ca7a1d105b.png">
this bit of code makes it say in console it is from school cheats and it cannot be reuploaded which is clearly being broken, if he had any knowledge of Blooket API he would realize the first part of code 
![image](https://user-images.githubusercontent.com/113489420/192832894-b4845c75-4e66-481e-91db-287dac12b058.png)
makes the script expire every 24 hours, it shows a watermark which is not his and just doesn't work because this 7 year old has no coding knowledge,  I will not be saying what code needs to be removed to make these scripts work due to the fact this person will do that and continue to act like they code. Heres [some working hacks](https://github.com/Minesraft2/Blooket-Cheats/tree/main/obfuscated) you should check out and support, I would also like to mention [@therealgliz](https://github.com/therealgliz) is fake so don't use his hacks, thanks for reading this, if this is edited it will show "edited by shenkeYT" so i have this copied in case. -vantro inc LLC

**Comment by vantr-o** [comment]
atleast have the watermark be your name LOL

**Comment by TheHelperMan** [comment]
Thank you very much for this information.

**Comment by vantr-o** [comment]
> Thank you very much for this information.

No problem, I'd rather put the truth out, the reason it isn't being updated is because school cheats is archived.
